### ISSUE TITLE
 [🚨] Potential Secrets Disclosed

### ISSUE THREAD

**Issue by jessica-25-github** [SAP/credential-digger-tests#7]
Hi @SAP,
It seems that you are disclosing some hardcoded secrets here:

https://github.com/SAP/credential-digger-tests/blob/97415a27c4981ad8456fb306a5de114c5a6ae4a4/file_b.txt#L5 

Best,
Github Monitor.
<img src='https://raw.githubusercontent.com/SAP/credential-digger/main/github_assets/Logo-CD-Mint_48.png' alt='drawing' width='36'/>

**Comment by marcorosa** [comment]
Hi @jessica-25-github I guess your tests are working well :)
Do you want me to keep this issue open or do you want me to close it?
